Provide a sensible diagnostic if a user forgets the tool
Previously, we defaulted to `atllbuild` in this case, and started
prompting them about missing atllbuild keys, e.g.

    fatal error: Unknown outputType nil

This is almost certainly the wrong thing to do, instead we should
provide a diagnostic requiring them to specify the tool.

Test coverage.

Close #41